### ISSUE TITLE
执行mvn clean package报错

### ISSUE THREAD

**Issue by zerochina2020** [sofastack-guides/sofa-ark-spring-guides#1]
## 操作
mvn clean package 或mvn clean install
## 报错内容
java.lang.ArrayIndexOutOfBoundsException: 0
## 环境信息
Apache Maven 3.8.5
Java version: 1.8.0_251, vendor: Oracle Corporation, runtime: 
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
## 详细日志
[package-error.log](https://github.com/sofastack-guides/sofa-ark-spring-guides/files/8499859/package-error.log)

**Comment by yuanyuancin** [comment]
> @yuanyuancin 1、能否辛苦看一下反馈这个问题，关注SOFA ARK小半年了，截止目前一个完整的示例都没跑起来。 2、另外示例中需要再xml中添加bean，项目中已经使用注解了，能否通过注解替换这个xml配置

1. use "mvn clean package -Dmaven.test.skip=true" instead of mvn clean package
2. 可以

**Comment by lvjing2** [comment]
时间过长，先关闭，有需要可以再开启
