### ISSUE TITLE
安装动态模块失败

### ISSUE THREAD

**Issue by AmarisEx** [sofastack-guides/sofa-ark-spring-guides#12]
![image](https://user-images.githubusercontent.com/43944845/171355492-8d5942fc-cdfc-412b-a62b-40baab80514a.png)
如图，拉下来的代码未改动，宿主项目成功运行，动态模块使用 biz -i 命令安装时提示端口已被占用（Web应用），如何解决？（宿主应用和动态模块不能在同一端口运行吗）

**Comment by lvjing2** [comment]
先给模块的tomcat更换一个端口，可以部署成功了。 
![image](https://user-images.githubusercontent.com/3754074/172142521-a0d317bb-0266-4c64-add9-0aa5501b0d44.png)

**Comment by AmarisEx** [comment]
Thanks
