### ISSUE TITLE
执行biz -i 后无反应

### ISSUE THREAD

**Issue by jxsrlsl1234** [sofastack-guides/sofa-ark-spring-guides#15]
动态新增ark-biz服务时，执行biz -i xxxx/xxx.jar后，如下
```shell
Start to process install command now, pls wait and check.

sofa-ark>biz -a
sofa-ark-spring-guides:1.0.0:activated
biz count = 1
```
间隔一分钟后查询也毫无反应，依然只有一个master biz
ark-biz 单独在IDEA里是可以启动成功的

**Comment by lvjing2** [comment]
完整 biz -i 命令发下，较大可能是命令格式不正确。看是否符合这个格式` biz -i file:///User/xxx/home/xxx/xxx.jar`

**Comment by lvjing2** [comment]
该 issue 长时间无回复，暂时关闭，有需要可以再开启
