### ISSUE TITLE
应用启动完成后端口又关闭了

### ISSUE THREAD

**Issue by m5jun** [sofastack-guides/sofa-ark-spring-guides#19]
![image](https://user-images.githubusercontent.com/1648064/191142072-e62c32fe-6096-49be-b367-0dd5f44d5462.png)

**Comment by lvjing2** [comment]
逻辑跑完了，就退出了呀

**Comment by lvjing2** [comment]
该 issue 长时间无回复，暂时关闭，有需要可以再开启
