### ISSUE TITLE
ark服务通信包版本问题

### ISSUE THREAD

**Issue by lwy91127** [sofastack-guides/sofa-ark-spring-guides#20]
sofa.ark.version 为2.0.0
使用ark服务通信能力时引入了包
`<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>runtime-sofa-boot-plugin</artifactId>
			<version>3.1.3</version>
		</dependency>`

但是该版本和2.0.0版本不匹配，启动时缺少类 com.alipay.sofa.ark.spi.event.BizEvent

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/7290237/191443824-cb2d520b-d801-41bc-880c-8bdb4ca24c44.png">

**Comment by gaosaroma** [comment]
建议使用最新版的sofa ark，sofa boot 和 sofa ark 结合的demo可以看看这个：https://github.com/sofastack-guides/sofa-ark-dynamic-guides

**Comment by lbj1104026847** [comment]
我使用了最新版本的sofa.ark.version 为2.1.3
使用了runtime服务通信能力：
<dependency>
	<groupId>com.alipay.sofa</groupId>
	<artifactId>runtime-sofa-boot-plugin</artifactId>
	<version>3.1.3</version>
</dependency>
也会报类找不到的错误，请问是啥原因呢？
![image](https://github.com/sofastack-guides/sofa-ark-spring-guides/assets/68089873/b24fef4f-f6e7-42b8-8778-d8ef0fcfff6e)

**Comment by lvjing2** [comment]
目前 springboot 是没有做过和 runtime-sofa-boot-plugin 的适配的， runtime-sofa-boot-plugin 是在 sofaboot 里是适配的，不过 springboot 的适配最近正在解决。

**Comment by lvjing2** [comment]
暂时关闭，有需要可以再开启
