### ISSUE TITLE
宿主应用和biz应用打包插件不一致

### ISSUE THREAD

**Issue by nisiyong** [sofastack-guides/sofa-ark-spring-guides#24]
* https://github.com/sofastack-guides/sofa-ark-spring-guides/blob/master/pom.xml
* https://github.com/sofastack-guides/spring-boot-ark-biz/blob/master/pom.xml

这个演示例子看起来已经是使用sofa-ark 2.0的模式了，打包插件也使用了`spring-boot-maven-plugin`，但是为啥另外一个biz应用还是使用原来的插件 `sofa-ark-maven-plugin`。

目前使用 `biz -i` 并没有达到描述的效果，想确认下都是用 `spring-boot-maven-plugin` 是否没有问题？演示例子是否需要更新下？

**Comment by gaosaroma** [comment]
没有问题的。

**Comment by nisiyong** [comment]
这边修改了 spring-boot-ark-biz 的pom.xml，将其maven插件改成与 master biz 的`spring-boot-maven-plugin` 一致。

```xml
 <plugin>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-maven-plugin</artifactId>
     <version>2.6.6</version>

     <configuration>
         <outputDirectory>target</outputDirectory>
         <classifier>ark-biz</classifier>
     </configuration>
     <executions>
         <execution>
             <id>package</id>
             <goals>
                 <goal>repackage</goal>
             </goals>
         </execution>
     </executions>
 </plugin>
```

使用这个插件构建后 master biz 执行 `biz -i `后无法动态加载，并且没有任何报错。
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/8198862/199873441-4545cd43-7266-44eb-829d-edaf9ce17e5c.png">

使用原来的 `sofa-ark-maven-plugin`构建后的包则可以动态加载。
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/8198862/199873699-cc6dcabd-708e-4d1f-b1be-9a10920e9b18.png">

**Comment by gaosaroma** [comment]
`spring-boot-ark-biz` 是一个 ark biz，它打包是需要使用 `sofa-ark-maven-plugin`的；
宿主应用需要用 `spring-boot-maven-plugin` 打包构建

**Comment by nisiyong** [comment]
好的 感谢解答
