### ISSUE TITLE
This feature requires ASM7

### ISSUE THREAD

**Issue by edanlx** [sofastack-guides/sofa-ark-spring-guides#26]
<groupId>com.alipay.sofa</groupId>
                <artifactId>sofa-ark-maven-plugin</artifactId>
                <version>2.0.4</version>
带包jdk11的springboot项目，大部分项目会出现

**Comment by edanlx** [comment]
应该是jdk11的兼容问题，在退回到jdk8不会

**Comment by lvjing2** [comment]
jdk 11 在最新版里已支持，该 issuse 暂时关闭
