### ISSUE TITLE
biz -i 安装插件时提示 Biz Name must not be empty!

### ISSUE THREAD

**Issue by DalianRollingKing** [sofastack-guides/sofa-ark-spring-guides#3]
当我使用本示例时希望通过telnet安装一个业务包，该业务包就是项目本身打出来的biz包，然而ark的日志却提示错误
![image](https://user-images.githubusercontent.com/42019170/166918415-4876ddbc-8bd9-4b67-b889-b47ab02a1ca8.png)
寻找其原因
![image](https://user-images.githubusercontent.com/42019170/166918513-a10a8a92-07fd-46a3-989f-a44726370353.png)
![image](https://user-images.githubusercontent.com/42019170/166918559-9b6efe1f-5986-44cd-85e6-31ac50aa506e.png)
![image](https://user-images.githubusercontent.com/42019170/166918816-1cf17969-fc8f-4c85-8d54-c0f1b5d6f525.png)
是否是基座的biz包并不能够被ark识别？如果我想要安装一个biz包，需要使用ark1.0的方式创建吗？

**Comment by DalianRollingKing** [comment]
我希望通过sofaark来作为业务与业务隔离，业务与平台隔离的类隔离解决方案组件，然而在我的第一步，最简单的版本，全部biz以pom依赖进来的时候，我并不知道如何进行合并部署，希望同样有一期教程，因为通常使用telnet或zk的形式部署会增加很多运维的工作量

**Comment by lylingzhen** [comment]
@yuanyuancin @lvjing2 看一下

**Comment by lvjing2** [comment]
> 我希望通过sofaark来作为业务与业务隔离，业务与平台隔离的类隔离解决方案组件，然而在我的第一步，最简单的版本，全部biz以pom依赖进来的时候，我并不知道如何进行合并部署，希望同样有一期教程，因为通常使用telnet或zk的形式部署会增加很多运维的工作量

模块的 application.properties 里设置了 application.name 吗？加上去再试下。

另外当前关于 telnet 来安装，我们后面会把我们内部使用的 sofaArk agent: Arklet 开源出来。

**Comment by yuanyuancin** [comment]
[sofa-ark-spring-guides](https://github.com/sofastack-guides/sofa-ark-spring-guides) 是一个master biz工程，打包出来的jar不是ark biz，是一个普通Spring executable jar，不能进行biz -i操作，动态模块使用 https://github.com/sofastack-guides/spring-boot-ark-biz

**Comment by yuanyuancin** [comment]
更新了readme，可以再看看

**Comment by DalianRollingKing** [comment]
> > 我希望通过sofaark来作为业务与业务隔离，业务与平台隔离的类隔离解决方案组件，然而在我的第一步，最简单的版本，全部biz以pom依赖进来的时候，我并不知道如何进行合并部署，希望同样有一期教程，因为通常使用telnet或zk的形式部署会增加很多运维的工作量
> 
> 模块的 application.properties 里设置了 spring.application.name 吗？加上去再试下。
> 
> 另外当前关于 telnet 来安装，我们后面会把我们内部使用的 sofaArk agent: Arklet 开源出来。

我在这里说明一下我目前遇到的问题，希望能够得到解决
1.我创建了一个biz应用，目前来看这一步没有什么问题
![image](https://user-images.githubusercontent.com/42019170/167061218-c1c8aae3-4f9c-4438-a611-b86263ee5632.png)
2.在master应用中我通过pom的形式依赖了第一步我创建的biz，这一步看起来也没什么问题
![image](https://user-images.githubusercontent.com/42019170/167061374-af18bd8e-f40e-4b6e-9fb8-7fb164a43611.png)
3.我希望在masterbiz启动的时候ark容器也会同时加载我的第一步创建的业务biz，我尝试在masterbiz工程使用两种打包方式，第一种是ark2.0官方推荐的springboot原生打包插件
![image](https://user-images.githubusercontent.com/42019170/167061578-11a8922f-ba8d-49cd-9405-141ecc82d9d0.png)
![image](https://user-images.githubusercontent.com/42019170/167061783-5d103183-262a-41d6-b844-b4d07433deeb.png)
![image](https://user-images.githubusercontent.com/42019170/167062165-3469c755-aa7c-4cca-b4ac-62c95cebd9fd.png)
![image](https://user-images.githubusercontent.com/42019170/167062242-80fee2db-de2d-4fd2-bdfc-980753326fa3.png)
发现biz模块只有一个，于是我尝试使用第二种方式
![image](https://user-images.githubusercontent.com/42019170/167062306-dd953f25-86a0-40b8-b151-495a9e7d0de5.png)
![image](https://user-images.githubusercontent.com/42019170/167062350-9aa9e950-72ec-41ea-857a-06921758e16a.png)
但是却发生了报错
![image](https://user-images.githubusercontent.com/42019170/167062416-8bd2ce39-2178-4d7d-9cf5-f55bba5d7500.png)
![image](https://user-images.githubusercontent.com/42019170/167062461-a4dead5f-e19a-4f40-8b4b-e7e97896f341.png)
所以我应该如何能够进行“静态合并部署”
